### ISSUE TITLE
Name Regex doesn't allow domains with hyphen

### ISSUE THREAD

**Issue by wilkejo** [conduktor/terraform-provider-conduktor#15]
Hello,

I tried to create a user with a domain including a hyphen. Error Message:

`Attribute name value must match regular expression '^([\w\-_.]*[^.])(@\w+)(\.\w+(\.\w+)?[^.\W])$', got: first.name@some-domain.com`

**Comment by qboileau** [comment]
Thank for the report.
Indeed, the regex used here is incorrect and should allow hyphen in domain part of email. 
We will provide a fix as soon as possible.
