### ISSUE TITLE
API returns data in a different order, so terraform sees a meaningless change?

### ISSUE THREAD

**Issue by wilkejo** [conduktor/terraform-provider-conduktor#16]
Hello conduktor team,

I tried the provider and have the following user setup.

```hcl
resource "conduktor_user_v2" "user" {
  name     = "first.name@somedomain.com"
  spec {
    firstname = "firstname"
    lastname  = "name"
    permissions = [
      {
        resource_type = "TOPIC"
        name          = "a-topic"
        cluster       = "test"
        pattern_type  = "PREFIXED"
        permissions   = local.topic_read_permissions
      },
      {
        resource_type = "TOPIC"
        name          = "b-topic"
        cluster       = "test"
        pattern_type  = "PREFIXED"
        permissions   = local.topic_read_permissions
      },
      {
        resource_type = "TOPIC"
        name          = "c-topic"
        cluster       = "test"
        pattern_type  = "PREFIXED"
        permissions   = local.topic_read_permissions
      }
    ]
  }
}
```

The first apply is fine. Now I'm doing a terraform plan and get following plan
```hcl
  # conduktor_user_v2.user will be updated in-place
  ~ resource "conduktor_user_v2" "user" {
        name = "first.name@somedomain.com"

      ~ spec {
          ~ permissions = [
              ~ {
                  ~ name          = "c-topic" -> "b-topic"
                    # (4 unchanged attributes hidden)
                },
              ~ {
                  ~ name          = "b-topic" -> "c-topic"
                    # (4 unchanged attributes hidden)
                },
                # (1 unchanged element hidden)
            ]
            # (2 unchanged attributes hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

I changed nothing and the user was not touched.

**Comment by allebacco** [comment]
I think that the solution should be to compare the list returned by the Console API and the `permissions` field not as a list, but as a set. This should fix the ordering problem and avoid the dependency on an internal behavior of the Console APIs.

**Comment by qboileau** [comment]
Indeed, this will fix the issue and the one on group members too. 
Thank you for the insight, listing this in our internal tracking system :+1:

**Comment by rd-michel** [comment]
i can confirm the issues and we're waiting for the fix.

thanks guys

**Comment by qboileau** [comment]
@rd-michel we are working on a fix for all the places we put a List instead of a Set.
We listed all those lists currently : 
`conduktor_user_v2` resource : 
- `/spec/permissions`
- `/spec/permissions/permissions`

`conduktor_group_v2` resource :
- `/spec/members`
- `/spec/members_from_external_groups`
- `/spec/external_groups`
- `/spec/permissions`
- `/spec/permissions/permissions`

**Comment by Stu-conduktor** [comment]
@wilkejo we've identified a fix and will look to release this soon alongside some additional functionality. Thanks for reporting the issue.

**Comment by wilkejo** [comment]
Thank you, Looking forward to the release

**Comment by Stu-conduktor** [comment]
@wilkejo - we're hoping to bring you a release this week if all goes to plan :).
